"""IMAP-to-Maildir sync job runner (via mbsync/isync).

Mirrors an IMAP account to a local Maildir — one directory per folder, one
file per message. The sync is strictly one-directional (``Sync Pull``): the
remote mailbox is never modified. With ``delete_destination`` (default true),
remote deletions propagate to the local copy, matching CloudDump's
current-state-mirror philosophy.

Designed to back up Proton Mail via Proton Bridge (a sidecar exposing IMAP on
127.0.0.1:1143), but works against any IMAP server — Gmail, Fastmail, etc.
"""

import os
import re
import tempfile
import time

import clouddump
from clouddump import cfg, log, run_cmd

# Hostnames, IPv4 literals, and docker service names — no shell/config metachars.
_HOST_RE = re.compile(r"^[a-zA-Z0-9._-]+$")

# CloudDump tls value -> mbsync TLSType
_TLS_TYPES = {"ssl": "IMAPS", "starttls": "STARTTLS", "none": "None"}


def _reject_config_chars(value):
    """True if an IMAP name (user/folder) would break the quoted mbsyncrc value.

    Rejects newline/CR/double-quote, plus backslash — mbsync treats backslash as
    an escape character even inside double quotes, so there is no safe way to
    pass one through a quoted IMAP name.
    """
    return any(c in value for c in "\n\r\"\\")


def _reject_path_chars(value):
    """True if a filesystem path would break the quoted mbsyncrc line.

    Paths are emitted inside double quotes, so newline/CR (line break / directive
    injection) and double-quote (break out of the value) are rejected. Backslash
    is allowed: it is a legal POSIX path char (and the path separator on Windows
    dev/test hosts), and the surrounding quotes keep it contained.
    """
    return any(c in value for c in "\n\r\"")


def _build_config(host, port, user, passfile, tls_type, cert_file,
                  destination, patterns, delete):
    """Render an mbsyncrc for a one-directional far->near (remote->local) sync."""
    cert_line = f'CertificateFile "{cert_file}"\n' if cert_file else ""

    if delete:
        # Full mirror: pull new/changed/deleted, and actually remove locally.
        sync_lines = "Create Near\nExpunge Near\nRemove Near\nSync Pull"
    else:
        # Pull new messages and flag changes only; never delete locally.
        # (No PullExpunge/PullGone, so local messages are never removed.)
        sync_lines = "Create Near\nSync PullNew PullFlags"

    return (
        "# Generated by CloudDump — do not edit\n"
        "IMAPAccount clouddump\n"
        f"Host {host}\n"
        f"Port {port}\n"
        f'User "{user}"\n'
        f'PassCmd "cat {passfile}"\n'
        f"TLSType {tls_type}\n"
        f"{cert_line}"
        "\n"
        "IMAPStore clouddump-remote\n"
        "Account clouddump\n"
        "\n"
        "MaildirStore clouddump-local\n"
        f'Path "{destination}/"\n'
        f'Inbox "{destination}/INBOX"\n'
        "SubFolders Verbatim\n"
        "\n"
        "Channel clouddump\n"
        "Far :clouddump-remote:\n"
        "Near :clouddump-local:\n"
        f"Patterns {patterns}\n"
        f"{sync_lines}\n"
        "SyncState *\n"
    )


def run_imap_sync(target, logfile_path):
    """Sync one IMAP account to a local Maildir using ``mbsync``."""
    host = cfg(target, "host")
    user = cfg(target, "user")
    password = cfg(target, "pass")
    destination = cfg(target, "destination")
    tls = cfg(target, "tls", "ssl")
    cert_file = cfg(target, "cert_file")
    delete = cfg(target, "delete_destination", True)
    exclude = cfg(target, "exclude", [])

    # Default port depends on transport: 993 for implicit TLS (IMAPS),
    # 143 for STARTTLS or plaintext.
    default_port = "993" if tls == "ssl" else "143"
    port = str(cfg(target, "port", default_port))

    if not host or not user or not password or not destination:
        log.error("Missing host, user, pass, or destination for imap account.")
        return 1

    if not _HOST_RE.match(host):
        log.error("Invalid host %s. Must be a hostname or IPv4 address (no special characters).", host)
        return 1

    tls_type = _TLS_TYPES.get(tls)
    if tls_type is None:
        log.error("Invalid tls '%s'. Must be one of: ssl, starttls, none.", tls)
        return 1

    # Every operator-supplied value is written into the generated mbsyncrc;
    # reject anything that could break out of a quoted value or inject a
    # directive. IMAP names use the stricter check (backslash is an mbsync
    # escape); paths are quoted, so they only reject line breaks / quotes.
    if _reject_config_chars(user):
        log.error("Invalid characters in imap user.")
        return 1
    for field, value in (("destination", destination), ("cert_file", cert_file)):
        if value and _reject_path_chars(value):
            log.error("Invalid characters in imap %s.", field)
            return 1
    for pat in exclude:
        if _reject_config_chars(pat):
            log.error("Invalid characters in imap exclude pattern %r.", pat)
            return 1

    os.makedirs(destination, exist_ok=True)

    # Patterns: all folders, minus any excluded ones (mbsync negation syntax).
    patterns = " ".join(["*"] + [f'!"{p}"' for p in exclude])

    log.info("Syncing via mbsync", extra={"host": host, "destination": destination})
    log.debug("Port: %s, user: %s, tls: %s, delete: %s", port, user, tls, delete)
    if exclude:
        log.info("Excluding %d folder pattern(s).", len(exclude))

    # Password goes in its own 0600 file (mkstemp default), referenced via
    # PassCmd — so the secret never lands in the mbsyncrc itself.
    pass_fd, passfile = tempfile.mkstemp(prefix="clouddump_imap_pass_")
    config_fd, configfile = tempfile.mkstemp(suffix=".mbsyncrc", prefix="clouddump_imap_")
    try:
        with os.fdopen(pass_fd, "w") as f:
            f.write(password)
        config = _build_config(host, port, user, passfile, tls_type,
                               cert_file, destination, patterns, delete)
        with os.fdopen(config_fd, "w") as f:
            f.write(config)

        cmd = ["mbsync", "-c", configfile]
        if clouddump.debug:
            cmd.append("-V")
        cmd.append("clouddump")

        t0 = time.time()
        rc = run_cmd(cmd, logfile_path=logfile_path)
        elapsed = int(time.time() - t0)

        if rc != 0:
            log.error("mbsync failed", extra={"host": host, "elapsed_s": elapsed})
        else:
            log.info("mbsync completed", extra={"host": host, "elapsed_s": elapsed})
        return rc
    finally:
        for path in (passfile, configfile):
            try:
                os.remove(path)
            except OSError:
                pass
