name: build
on: [push, pull_request]

env:
  APP_NAME: 'clouddump'

jobs:

  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
       distro: [ fedora, opensuse, ubuntu ]

    steps:
      - uses: actions/checkout@v3

      - name: Set version
        run: echo "version=$(cat VERSION | head -n 1)" >> $GITHUB_ENV

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          cp vnclouddump-${{matrix.distro}}/Dockerfile .
          docker build ${{github.workspace}}
