name: Integration test
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build:
    if: (!contains(github.event.head_commit.message, 'skip ci')) && github.event.pull_request.draft == false

    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
       distro: [ fedora, opensuse, ubuntu ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          cp vnclouddump-${{matrix.distro}}/Dockerfile .
          docker build ${{github.workspace}}