name: shellcheck
on: [push, pull_request]

jobs:
  shellcheck:
    name: Shell Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.2.0
      - name: Install shellcheck
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt install -y shellcheck
      - name: shellcheck
        run: |
          shellcheck -s bash --exclude=SC2181 --exclude=SC2230 scripts/vnclouddump-start.sh
          shellcheck -s bash --exclude=SC2181 --exclude=SC2230 --exclude=SC2086 --exclude=SC2001 scripts/vnclouddump-wrapper.sh
          shellcheck -s bash --exclude=SC2181 --exclude=SC2230 scripts/azdump.sh
          shellcheck -s bash --exclude=SC2181 --exclude=SC2230 --exclude=SC2086 scripts/pgdump.sh
