name: Shellcheck
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  shellcheck:
    name: Shell check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: './scripts'
          ignore_paths: './scripts/azcopy-install.sh'
          severity: warning
          additional_files: 'start.sh wrapper.sh azdump.sh pgdump.sh'
        env:
          SHELLCHECK_OPTS: --exclude=SC2181 --exclude=SC2230 --exclude=SC2086 --exclude=SC2001 --exclude=SC2317

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build ${{github.workspace}}